on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Run your project's build step
      # - name: Build
      #   run: npm install && npm run build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: "eOPm8_xG_noLVKwLpkm5qrLJuET9vvoPbITPhaQu"
          accountId: "06d3d6420591cd7e469ba8fb4ab764fa"
          projectName: "shubhamkosta-lucifer-devil" # e.g. 'my-project'
          directory: "/" # e.g. 'dist'
          gitHubToken: "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"
