on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "06d3d6420591cd7e469ba8fb4ab764fa"
          projectName: "shubhamkosta-lucifer-devil"
          directory: "/" # Update this to the correct directory
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: 2
